using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bomber : MonoBehaviour
{
    //CONSIDERO QUE LOS AGENDES DEBERIAN DE HEREDAR DE AGENT BASE Y NO DE AGENT YA QUE SOLO NECESITAMOS LOS COMPORTAMIENTOS DEL STEERING PARA HACER QUE FUNCIONE ESTA WEA
    //EN ESTE SCRIPT SOLO MANEJAMOS LOS ESTADOS LA UNIDAD COMO SU FUNCION DE ATAQUE, CAMINAR, ETC.
    //ESTE MENSO ES IGUAL QUE EL RANGE SOLO QUE ESTE EN VEZ DE HACER DAÑO A UNA UNIDAD EN ESPECIFICO DAÑA A TODAS LAS UNIDADES DENTRO DE UN AREA
    //PARA ESTO SE ME OCURRE QUE DENTRO DE SU RANGO DE ATAQUE, SI DETECTA A UNA UNIDAD EN VEZ DE ATACARLA INSTANCIE UNA "BOMBA" QUE HAGA DAÑO A LAS UNIDADES ENEMIGAS
    //ESTA BOMBA YA TENDRA SU ATQUE Y SU DAÑO EN AREA, CREO QUE SERIA MÁS FACIL DE PROGRAMAR YA QUE SOLO SERIA HACER DOS PREFABS DE BOMBAS UNA PARA BOMBAS QUE HACEN DAÑO AL PLAYER Y OTRA QUE HACE DAÑO A LA IA

    private void Attack()
    {

    }

    private void GoToTower()
    {

    }
}
