using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Cannon : MonoBehaviour
{
    [SerializeField] Unit unit;
    //ESTA MADRE NO HEREDA NADA YA QUE NO LO OCUPA
    //EN ESTE SCRIPT SOLO MANEJAMOS LOS ESTADOS LA UNIDAD COMO SU FUNCION DE ATAQUE, ETC.
    //ESTA MADRE FUNCIONA IGUAL QUE LAS TORRES SOLO QUE ATACA POR PRIORIDAD Y NO POR EL QUE TENGA MENOR VIDA
    //HAY QUE AGREGARLE UNA FUNCION DONDE VA PERDIENDO VIDA HASTA DESAPARECER YA QUE ESTA UNIDAD NO ES ETERNA

   
}
