using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class General : MonoBehaviour
{
    //ESTA MADRE NO HEREDA NADA YA QUE NO LO OCUPA
    //EN ESTE SCRIPT SOLO MANEJAMOS LOS ESTADOS LA UNIDAD COMO SU FUNCION DE BUFEAR, ETC.
    //ESTA MADRE DETECTA A TODAS LAS UNIDADES ALIADAS Y CAMBIA SU VELOCIDAD DE MOVIMIENTO Y MEJORA SU ATAQUE (DETECTANDO EL SCRIPT UNIT Y SUMANDO X CANTIDAD A LA VELOCIDAD Y AL ATAQUE BASTARIA PARA MEJORAR A LAS UNDIADES)
    //HAY QUE AGREGARLE UNA FUNCION DONDE VA PERDIENDO VIDA HASTA DESAPARECER YA QUE ESTA UNIDAD NO ES ETERNA

    private void BUFEARPENDEJOS()
    {
        //PODEMOS COPIAR LAS MISMAS VARIABLES DEL PLAYER MANAGER PARA GENERAR ORO Y LA CORRTUNIA QUE ES PARA GENERAR ORO
    }

    private void MEDESAPAREZCO()
    {
        //CON UNA CORRUTINA SERIA FACILITO ESTA
    }
}
