using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Miner : MonoBehaviour
{
    //ESTA MADRE NO HEREDA NADA YA QUE NO LO OCUPA
    //EN ESTE SCRIPT SOLO MANEJAMOS LOS ESTADOS LA UNIDAD COMO SU FUNCION DE GENERAR RECURSOS, ETC.
    //ESTA MADRE FUNCIONA IGUAL A LA FUNCION DE MININGGOLD DEL PLAYER MANAGER
    //HAY QUE AGREGARLE UNA FUNCION DONDE VA PERDIENDO VIDA HASTA DESAPARECER YA QUE ESTA UNIDAD NO ES ETERNA

    private void GENERARORO()
    {
        //PODEMOS COPIAR LAS MISMAS VARIABLES DEL PLAYER MANAGER PARA GENERAR ORO Y LA CORRTUNIA QUE ES PARA GENERAR ORO
    }

    private void MEDESAPAREZCO()
    {
        //CON UNA CORRUTINA SERIA FACILITO ESTA
    }
}
