using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Miner : MonoBehaviour
{
    [SerializeField] Unit unit;
    //ESTA MADRE NO HEREDA NADA YA QUE NO LO OCUPA
    //EN ESTE SCRIPT SOLO MANEJAMOS LOS ESTADOS LA UNIDAD COMO SU FUNCION DE GENERAR RECURSOS, ETC.
    //ESTA MADRE FUNCIONA IGUAL A LA FUNCION DE MININGGOLD DEL PLAYER MANAGER
    //HAY QUE AGREGARLE UNA FUNCION DONDE VA PERDIENDO VIDA HASTA DESAPARECER YA QUE ESTA UNIDAD NO ES ETERNA

    
}
