using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Tank : MonoBehaviour
{
    //CONSIDERO QUE LOS AGENDES DEBERIAN DE HEREDAR DE AGENT BASE Y NO DE AGENT YA QUE SOLO NECESITAMOS LOS COMPORTAMIENTOS DEL STEERING PARA HACER QUE FUNCIONE ESTA WEA
    //EN ESTE SCRIPT SOLO MANEJAMOS LOS ESTADOS LA UNIDAD COMO SU FUNCION DE ATAQUE, CAMINAR, ETC.
    //ESTE MENSO ATRAE EL ATAQUE DE LOS ENEMIGOS ESTE SE PROGRAMA SOLO CON SOLO SUBIRLE SU PRIORIDAD, TAMBIEN ATACA PERO MUY POQUITO
    //SUS PRIORIDADES SON ESTRUCTURAS COMO LA TORRE, CAÑONES, MINERO O GENERAL

    private void Attack()
    {

    }

    private void GoToTower()
    {

    }
}
